const {
  BTC_NATIVE_SYMBOL,
  ETH_NATIVE_ADDR,
  ETH_NATIVE_SYMBOL,
} = require("./constant");

const coins_mainnet = [
  {
    name: "G Token",
    symbol: "GTOKEN",
    address: "0x2079413984EAf42602262D71AD48304E54159585",
    decimals: 18,
    showOnBuy: true,
    logo: "g-token.png",
    is_native: false,
    icon_url: "/images/g-token.png",
    viewOrder: 1,
  },
  {
    name: "EU/US",
    symbol: "EUUS",
    address: "0x735AcDEDd91a80334Ff72f07BFf41E1eEcF26677",
    decimals: 18,
    showOnBuy: false,
    logo: "eu_us.png",
    is_native: false,
    icon_url: "/images/eu_us.png",
    viewOrder: 2,
  },
  {
    name: "US/EU",
    symbol: "USEU",
    address: "0xE07ECC676daf0B24B24a1c46c966D9C463984B38",
    decimals: 18,
    showOnBuy: false,
    logo: "us_eu.png",
    is_native: false,
    icon_url: "/images/us_eu.png",
    viewOrder: 3,
  },
  {
    name: "BTC",
    symbol: BTC_NATIVE_SYMBOL,
    address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599", // fet getting price, used to WBTC address on ethereum
    decimals: 8,
    showOnBuy: true,
    logo: "bitcoin.png",
    is_native: true,
    icon_url: "/images/bitcoin.png",
    viewOrder: 4,
  },
  {
    name: "ETH",
    symbol: ETH_NATIVE_SYMBOL,
    address: ETH_NATIVE_ADDR,
    decimals: 18,
    showOnBuy: true,
    logo: "ethereum-eth.png",
    is_native: true,
    icon_url: "/images/ethereum.png",
    viewOrder: 5,
  },
  {
    name: "Tether USD",
    symbol: "USDT",
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    decimals: 6,
    showOnBuy: true,
    logo: "tether-usdt.png",
    is_native: false,
    icon_url: "/images/tether-usdt.png",
    viewOrder: 6,
  },
  {
    name: "Wrapped ETH",
    symbol: "WETH",
    address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    decimals: 18,
    showOnBuy: true,
    logo: "ethereum.png",
    is_native: false,
    icon_url: "/images/ethereum.png",
    viewOrder: 7,
  },
  {
    name: "USDC",
    symbol: "USDC",
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    decimals: 6,
    showOnBuy: true,
    logo: "usd-coin-usdc.png",
    is_native: false,
    icon_url: "/images/usdc.png",
    viewOrder: 8,
  },
  {
    name: "Wrapped BTC",
    symbol: "WBTC",
    address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    decimals: 8,
    showOnBuy: true,
    logo: "bitcoin-btc.png",
    is_native: false,
    icon_url: "/images/wrapped-bitcoin-wbtc.png",
    viewOrder: 9,
  },
];

const coins_testnet = [
  {
    name: "G Token",
    symbol: "GTOKEN",
    address: "0x2079413984EAf42602262D71AD48304E54159585",
    decimals: 18,
    showOnBuy: true,
    logo: "g-token.png",
    is_native: false,
    icon_url: "/images/g-token.png",
    viewOrder: 1,
  },
  {
    name: "EU/US(TEST)",
    symbol: "EUUS",
    address: "0xDd92b7237a99D907DfcB016eD2BC915abd5d5A72",
    decimals: 18,
    showOnBuy: false,
    logo: "eu_us.png",
    is_native: false,
    icon_url: "/images/eu_us.png",
    viewOrder: 2,
  },
  {
    name: "US/EU(TEST)",
    symbol: "USEU",
    address: "0xEA7900569A5713aCA01D169f9a0EA7668F470F08",
    decimals: 18,
    showOnBuy: false,
    logo: "us_eu.png",
    is_native: false,
    icon_url: "/images/us_eu.png",
    viewOrder: 3,
  },
  {
    name: "BTC (testnet)",
    symbol: BTC_NATIVE_SYMBOL,
    address: "0xc7de7afD0449E0B90c73d984b3094CB4212441FF",
    decimals: 8,
    showOnBuy: true,
    logo: "bitcoin.png",
    is_native: true,
    icon_url: "/images/bitcoin.png",
    viewOrder: 4,
  },
  {
    name: "ETH (Sepolia)",
    symbol: ETH_NATIVE_SYMBOL,
    address: ETH_NATIVE_ADDR,
    decimals: 18,
    showOnBuy: true,
    logo: "ethereum-eth.png",
    is_native: true,
    icon_url: "/images/ethereum.png",
    viewOrder: 5,
  },
  {
    name: "USDT (Sepolia)",
    symbol: "USDT",
    address: "0xb8250c0fa47f7e649a7fc022901507917e8ebf2f",
    decimals: 6,
    showOnBuy: true,
    logo: "tether-usdt.png",
    is_native: false,
    icon_url: "/images/tether-usdt.png",
    viewOrder: 6,
  },
  {
    name: "WETH (Sepolia)",
    symbol: "WETH",
    address: "0x931baA1d378d3135E4eD24531c5Eb7A93b01D44c",
    decimals: 18,
    showOnBuy: true,
    logo: "ethereum-eth.png",
    is_native: false,
    icon_url: "/images/ethereum.png",
    viewOrder: 7,
  },
  {
    name: "USDC (Sepolia)",
    symbol: "USDC",
    address: "0xf93c074ff481cFa20BA1784b71A142A16e2e1f57",
    decimals: 6,
    showOnBuy: true,
    logo: "usd-coin-usdc.png",
    is_native: false,
    icon_url: "/images/usdc.png",
    viewOrder: 8,
  },
  {
    name: "Wrapped BTC(Sepolia)",
    symbol: "WBTC",
    address: "0xc7de7afD0449E0B90c73d984b3094CB4212441FF",
    decimals: 8,
    showOnBuy: true,
    logo: "bitcoin-btc.png",
    is_native: false,
    icon_url: "/images/wrapped-bitcoin.png",
    viewOrder: 9,
  },
];

module.exports = {
  coins_mainnet,
  coins_testnet,
};
